dataset_config:
    data_dir: /home/hld/CLionProjects/HEAT_MPI/LightGCN/Data/yelp2018
    data_format: txt
    separator: ' '
    train_data: train.txt
    test_data: test.txt

model_config:
    num_negs: 8
    max_his: 100
    embedding_dim: 4
    neg_sampler: 1
    tile_size: 32
    mini_batch_size: 4
    refresh_interval: 512
    embedding_dropout: 0
    similarity_score: dot
    loss: PairwiseLogisticLoss
    metrics: ['Recall(k=20)', 'Recall(k=50)', 'NDCG(k=20)', 'NDCG(k=50)', 'HitRate(k=20)', 'HitRate(k=50)']
    optimizer: sgd
    milestones: [10]
    learning_rate: 1.e-2
    clip_val: 0.1
    embedding_regularizer: 1.e-7
    net_regularizer: 0
    net_dropout: 0
    epochs: 8
    eval_interval: 10
    seed: 2022