dataset_config:
    data_dir: /home/hld/HEAT/LightGCN/Data/amazon-book
    data_format: txt
    separator: ' '
    train_data: train.txt
    test_data: test.txt

model_config:
    num_negs: 16
    max_his: 100
    embedding_dim: 64
    neg_sampler: 0
    tile_size: 512
    refresh_interval: 8192
    embedding_dropout: 0
    similarity_score: dot
    loss: PairwiseLogisticLoss
    metrics: ['Recall(k=20)', 'Recall(k=50)', 'NDCG(k=20)', 'NDCG(k=50)', 'HitRate(k=20)', 'HitRate(k=50)']
    optimizer: sgd
    milestones: [10]
    learning_rate: 1.e-2
    clip_val: 1.0
    embedding_regularizer: 1.e-7
    net_regularizer: 0
    net_dropout: 0
    epochs: 5
    eval_interval: 2
    seed: 2022